const ACCESS_TOKEN = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijkl1234567890";
const ACCESS_TOKEN_TIME_LIFE = "3m";

const REFRESH_TOKEN = "abcdefghijklmpqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTWXYZ";
const REFRESH_TOKEN_TIME_LIFE = "10m";

module.exports = {
    ACCESS_TOKEN: ACCESS_TOKEN,
    ACCESS_TOKEN_TIME_LIFE: ACCESS_TOKEN_TIME_LIFE,
    REFRESH_TOKEN: REFRESH_TOKEN,
    REFRESH_TOKEN_TIME_LIFE: REFRESH_TOKEN_TIME_LIFE
}